### Create user
POST {{url}}/users
Authorization: Bearer testtest
Content-Type: application/json

{
  "count": 5
}

### Append user
POST {{url}}/users
Authorization: Bearer testtest
Content-Type: application/json

{
  "count": 5,
  "append": true
}

### convert to csv
POST {{url}}/export
Authorization: Bearer testtest
Content-Type: application/json
Accept: text/csv

[
  {
    "database": "db060",
    "password": "on-dog-8",
    "user": "u_060"
  },
  {
    "database": "db061",
    "password": "clean-tarpon-0",
    "user": "u_061"
  },
  {
    "database": "db062",
    "password": "tough-gar-4",
    "user": "u_062"
  },
  {
    "database": "db063",
    "password": "clean-dove-0",
    "user": "u_063"
  },
  {
    "database": "db064",
    "password": "finer-ibex-0",
    "user": "u_064"
  }
]

### export to pdf
POST {{url}}/export
Authorization: Bearer testtest
Content-Type: application/json
Accept: application/pdf

[
  {
    "database": "db060",
    "password": "on-dog-8",
    "user": "u_060"
  },
  {
    "database": "db061",
    "password": "clean-tarpon-0",
    "user": "u_061"
  },
  {
    "database": "db062",
    "password": "tough-gar-4",
    "user": "u_062"
  },
  {
    "database": "db063",
    "password": "clean-dove-0",
    "user": "u_063"
  },
  {
    "database": "db064",
    "password": "finer-ibex-0",
    "user": "u_064"
  }
]

### delete user u_002
DELETE {{url}}/user/u_002
Authorization: Bearer testtest
Accept: application/json

###
# curl -X DELETE --location "http://localhost:5555/user/u_008"
#    -H "Authorization: Bearer testtest"
#    -H "Accept: application/json"
DELETE http://localhost:5555/user/u_007
Authorization: Bearer testtest
Accept: application/json

###
GET {{url}}/databases/count
Authorization: Bearer testtest

###
GET {{url}}/users
Authorization: Bearer testtest
Content-Type: application/json

###
GET {{url}}/users
Authorization: Bearer testtest
Accept: text/csv

### login ok
POST {{url}}/login
Authorization: Bearer testtest

### login fail
POST {{url}}/login
Authorization: Bearer fail
